name: test en commit o pull request en main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mensaje-on-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar el codigo del repositorio
        uses: actions/checkout@v4
      
      - name: Configurar JDK del proyecto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Construccion y analisis con Sonarqube y JaCoCo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar \
            -Dsonar.projectKey=MartinMonje00_EV_2_MartinMonjeAlvarez_DOY0101_004D \
            -Dsonar.organization=martinmonje00 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Subida artefacto JAR
        uses: actions/upload-artifact@v4
        with:
          name: app.jar
          path: target/*.jar
